# Generated by Django 5.2.7 on 2025-10-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('score', models.IntegerField(verbose_name='Бал')),
                ('total', models.IntegerField(verbose_name='Всього питань')),
                ('percentage', models.FloatField(verbose_name='Відсоток')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Спроба тесту',
                'verbose_name_plural': 'Спроби тестів',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Текст питання')),
                ('option_a', models.CharField(max_length=200, verbose_name='Варіант A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Варіант B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Варіант C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Варіант D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Правильна відповідь')),
                ('category', models.CharField(max_length=50, verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Питання тесту',
                'verbose_name_plural': 'Питання тестів',
            },
        ),
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(verbose_name='Опис')),
                ('youtube_url', models.URLField(verbose_name='YouTube URL')),
                ('duration', models.CharField(max_length=10, verbose_name='Тривалість')),
                ('order', models.IntegerField(verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Відео урок',
                'verbose_name_plural': 'Відео уроки',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Електронна пошта')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_registered', models.BooleanField(default=False, verbose_name='Зареєстрований')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенти',
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Бал')),
                ('total_questions', models.IntegerField(default=50, verbose_name='Загальна кількість питань')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='Завершено')),
                ('recommendations', models.TextField(blank=True, verbose_name='Рекомендації')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Результат тесту',
                'verbose_name_plural': 'Результати тестів',
            },
        ),
    ]
